### ISSUE TITLE
JSON output is wrapped in CSS comments

### ISSUE THREAD

**Issue by conormuirhead** [ThinkUniform/uniformcss#23]
When using `output: "json"`, the resulting output is invalid JSON due to wrapping comments like so:

```
/*! UniformCSS v1.3.0 | MIT License | github.com/ThinkUniform/uniformcss */
/*!
{ ... }
*/
```

**Expected behavior**
I would expect raw JSON to be output, that doesn't require me to manually remove wrapping comments.

**Additional context**
I've setup Uniform with my application using a config/_index.scss file that does something along these lines:

```
$output-mode: "css" !default;

@use "uniform" as * with (
  $config: (
    // Build settings - https://uniformcss.com/docs/build-settings/
    delimiter: "\\:",
    pseudo-delimiter: ":",
    screen-delimiter: ":",
    output: $output-mode,
    ...
  )
)
```

Then I have two separate stylesheets that I use, one (application.sass.scss) generates the CSS for my app:

```
// Generated utilities - configs + generation
@use "app/config/index";
@use "app/custom/button";
...
```

And the other (reference.sass.scss) generates the JSON for our internal CSS reference docs:

```
@use "app/config/index" with ( $output-mode: 'json' );
```

My build setup for reference.sass.scss drops the output in a `css-utilities.json` file that we consume to automatically generate documentation. But...with the current issue described up top, a manual intervention is required to remove the wrapping comments from the JSON output. What do you think of removing the wrapping comments @jinsupark?

**Comment by jinsupark** [comment]
Hey @conormuirhead! After some experimentation, I don't think there will be a way to output this without the wrapping comments, unfortunately. This is due to how Sass handles interpolation. More specifically, interpolation cannot be standalone and expects the `{` selector to follow. How Uniform compiles JSON is similar to how https://github.com/oddbird/sass-json-export works.

I will reach out to the core Sass team to request a simple string print functionality in order to get around this problem.

**Comment by conormuirhead** [comment]
I appreciate you investigating @jinsupark! Good news is we've got a workaround in place for the moment, just by adding some extra steps to our build script for generating the json.
